### ISSUE TITLE
[Proposal] Add UUID property

### ISSUE THREAD

**Issue by Renegade334** [phergie/phergie-irc-connection#3]
Plugins that rely on storing data for different connections currently have to generate some kind of unique key based on publicly accessible properties of the `Connection` object.

Instead, the `Connection` constructor could generate and store a UUID property, and `ConnectionInterface` could implement a `getUniqueId()` function for accessing it.

**Comment by elazar** [comment]
Not sure this is really needed. Plugins could use an instance of [`\SplObjectStorage`](http://php.net/splobjectstorage) keyed by `ConnectionInterface` instance or [`spl_object_hash()`](http://php.net/spl_object_hash) in conjunction with a normal PHP array to accomplish the same thing.
