### ISSUE TITLE
Add a method to get the connection mask

### ISSUE THREAD

**Issue by elazar** [phergie/phergie-irc-connection#5]
This is currently used in the [client](https://github.com/phergie/phergie-irc-client-react/blob/94f131905986f542342199672ce2946f60d893e0/src/Client.php#L284-289) and the [EventFilter](https://github.com/phergie/phergie-irc-plugin-react-eventfilter/blob/5d21541025745f6dbf1ee132ebf183d553d54105/src/UserFilter.php#L63-67), [FeedTicker](https://github.com/phergie/phergie-irc-plugin-react-feedticker/blob/d6a067a0873789e9044dea540f1f6ca0317361e9/src/Plugin.php#L364-371), and [Bridge](https://github.com/phergie/phergie-irc-plugin-react-bridge/blob/9dbe9bf0273004ceeaa53c6840981ccaaea8e848/src/Plugin.php#L146-153) plugins.

**Comment by Renegade334** [comment]
NB that it's not used in EventFilter.

Also, it should be expressly stated that the connection mask should not be used as a key by which to store connection-specific data, as it can change during the session. Data keyed by connection should be stored as attached data in an `SplObjectStorage` instance.

**Comment by Renegade334** [comment]
On the subject of storing the event queue for each connection, what about `EventQueueFactoryAwareInterface`?

**Comment by elazar** [comment]
Merged #6.
